# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Quakes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quakes

pod "Macaw", "0.9.6"

  target 'QuakesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
